In [13]:
import pandas as pd

df = pd.read_csv('./fsdata/Is삼성생명.csv', index_col = 0)

In [14]:
df

,Income statement(Unit: KRW),20100401-20110331,20090401-20100331,20080401-20090331,20070401-20080331,20060401-20070331,20050401-20060331,20040401-20050331,20030401-20040331,20020401-20030331,20010401-20020331,20000401-20010331,19990401-20000331
NaN,label_ko,"('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)","('연결재무제표',)"
0.0,Ⅰ.영업수익,26230238000000.0,25761194000000.0,25344934000000.0,24613063000000.0,23904064000000.0,23287239000000.0,23640095000000.0,22718308000000.0,23834342000000.0,22842361000000.0,24781630539000.0,20852208086000.0
1.0,1.보험료수익(주석21),14607546000000.0,14523218000000.0,14697681000000.0,15382579000000.0,15460008000000.0,15547303000000.0,16070475000000.0,16387255000000.0,17097752000000.0,16794111000000.0,19235766044000.0,15062541468000.0
2.0,가.개인보험료,14138120000000.0,14032980000000.0,14152390000000.0,14785807000000.0,14807806000000.0,14787199000000.0,15211461000000.0,15540538000000.0,15750913000000.0,14847242000000.0,16893631300000.0,11779572869000.0
3.0,나.단체보험료,469426000000.0,490238000000.0,545291000000.0,596772000000.0,652202000000.0,760104000000.0,859014000000.0,846717000000.0,1346839000000.0,1946869000000.0,2342134744000.0,3282968599000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97.0,1.지배회사지분순이익,1924853000000.0,906095000000.0,113658000000.0,715945000000.0,514580000000.0,624360000000.0,575614000000.0,327801000000.0,861110000000.0,630789000000.0,246588422000.0,396004765000.0
98.0,2.소수주주지분순이익,-3523000000.0,-374000000.0,332000000.0,3058000000.0,3776000000.0,NaN,2963166000000.0,NaN,NaN,2648805000000.0,2714541911000.0,NaN
99.0,Ⅸ.지배회사지분순이익의주당이익(주석28),NaN,NaN,NaN,NaN,NaN,NaN,2963166000000.0,NaN,NaN,2648805000000.0,2714541911000.0,NaN
100.0,1.기본주당순이익(단위:원),9624.0,4530.0,568.0,35797.0,25729.0,NaN,2963166000000.0,NaN,NaN,2648805000000.0,2714541911000.0,NaN
101.0,2.희석주당순이익(단위:원),9624.0,4530.0,568.0,35797.0,25729.0,NaN,2963166000000.0,NaN,NaN,2648805000000.0,2714541911000.0,NaN